# Server Configuration
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/mockupdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mockupuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mockuppass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.mockup=DEBUG

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

# Security Configuration
token.jwt=71266gdb127HNJ761238jk98kjasdh12388123712737123asd12737yvfgbhbutvfgybhknjdgxfcvjhknjvgdfhfhgbhjn894okedurirkedjf8r9o4ewsw

security.user.name=admin
security.user.password=admin
security.user.role=USER,ADMIN
